### ISSUE TITLE
redundant?

### ISSUE THREAD

**Issue by malhal** [travisjeffery/TRVSURLSessionOperation#2]
Just use sessionWithConfiguration and specify a queue:
https://gist.github.com/akhenakh/7027747

**Comment by travisjeffery** [comment]
no the point is to have NSOperations and an NSOperationQueue which are more powerful and gives you more control

**Comment by malhal** [comment]
NSURLSession is conceptually an operation queue. It already is powerful and has all the control needed. E.g. make downloads sequential by setting HTTPMaximumConnectionsPerHost to 1. Set request priority with priority property, e.g  NSURLSessionTaskPriorityHigh. 

In the past it might have been an idea to wrap NSURLConnection in an operation queue, but that is exactly what Apple have provided with NSURLSession. Wrapping it in another queue seems unnecessary. See this answer for more info: http://stackoverflow.com/a/24414286/259521
